project: 
  type: website
  output-dir: docs

website:
  title: "Murphy John's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Data Analysis Exercise"
            file: cdcdata-exercise/code/cdcdata-exercise.qmd
          - text: "Fitting Exercise"
            file: fitting-exercise/code/fitting-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "Synthetic Data Exercise"
            file: synthetic-data-exercise/synthetic-data-exercise.qmd
          - text: "Tidy Tuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
          
    right:
      - icon: github 
        href: https://github.com/murphyhjohn/murphyjohn-MADA-portfolio.git       

format:
  html:
    theme: default
    highlight: zenburn
    css: styles.css
    toc: FALSE


